# monitoring/prometheus.yml
# Configuration du scraping de métriques Prometheus

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "jiji-api"
    static_configs:
      - targets: ["api:5000"]
    metrics_path: /metrics
